#!/bin/python3

import os
import sys

default = str(1)

if len(sys.argv) > 1:
    amount = str(sys.argv[1])
else:
    amount = str(1)


if (os.path.exists("/home/pjackim/.config/eww/_gray.scss")):
    file = open("/home/pjackim/.config/eww/_gray.scss", mode='r')
    for line in file.readlines():
        if amount not in line:
            file.close()
            os.system("echo '$test: "+amount+";' > /home/pjackim/.config/eww/_gray.scss")
            os.system("cp /home/pjackim/.config/nitrogen/bg-gray.cfg.bak /home/pjackim/.config/nitrogen/bg-saved.cfg")
            
        else:
            os.system("echo '$test: "+default+";' > /home/pjackim/.config/eww/_gray.scss")
            os.system("cp /home/pjackim/.config/nitrogen/bg-saved.cfg.bak /home/pjackim/.config/nitrogen/bg-saved.cfg")
else:
    os.system("echo '$test: "+default+";' > /home/pjackim/.config/eww/_gray.scss")
    
os.system("echo '' >> /home/pjackim/.config/eww/eww.scss")
os.system("nitrogen --restore")
