#! /bin/sh

# Monitor Layout
$HOME/.screenlayout/monitor_layout_3.sh & 


# Picom
$HOME/.config/picom/picom_launcher &

# Nitrogen
nitrogen --restore &

# SXHKD
sxhkd &

# Polybar
$HOME/.config/polybar/shapes/launch.sh &

# Workspace Initialization
bspc monitor DP-1 -d dp1 dp2 dp3 dp4 dp5 dp6 dp7 dp8 dp9 dp10               # center
bspc monitor HDMI-0 -d hd1 hd2 hd3 hd4 hd5 hd6 hd7 hd8 hd9 hd0    # left
bspc monitor DP-3 -d v1 v2 v3 v4 v5 v6 v7 slack teams    # Vert


bspc config normal_border_color \#836A50
bspc config focused_border_color \#D9A362

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

height_full=937 height_half=462 

left_x=5 right_x=1434
center_x=491
y_top=71 y_mid=543
width=477 center_width=938

# General Rules
bspc rule -a konsole:term_f state=floating rectangle="400"x"500"+"760"+"340"

# bspc rule -a Code state=floating rectangle="1000"x"$height_full"

#bspc rule -a konsole_desktop desktop='^11' state=floating rectangle="481"x"410"+"3355"+"595" layer=BELOW border=off
bspc rule -a clear:integrated_terminal_0 desktop='^11' state=floating rectangle="481"x"410"+"3355"+"595" layer=below border=off
bspc rule -a clear:integrated_terminal_1 desktop='^21' state=floating rectangle="950"x"410"+"3911"+"50" layer=below border=off

bspc rule -a feh state=floating
bspc rule -a thunar state=floating

bspc rule -a yakuake state=floating rectangle="768"x"1050"+"0"+"30"


# Monitor 2
#   Workspace 1
#       Terminal 1
bspc rule -a konsole:autostart_term1 desktop='^11' state=floating rectangle="$width"x"$height_full"+"$left_x"+"$y_top"
#       Terminal 2
bspc rule -a konsole:autostart_term2 desktop='^11' state=floating rectangle="$center_width"x"$height_full"+"$center_x"+"$y_top"
#       Terminal 3
bspc rule -a konsole:autostart_term3 desktop='^11' state=floating rectansgle="$width"x"$height_half"+"$right_x"+"$y_top"
#       Terminal 4
bspc rule -a konsole:autostart_term4 desktop='^11' state=floating rectangle="$width"x"$height_half"+"$right_x"+"$y_mid"





# Monitor 1
#   Workspace 1
#       Htop
bspc rule -a konsole_desktop:autostart_htop desktop='^1' state=floating rectangle="$width"x"$height_full"+"$left_x"+"$y_top" layer=below border=off
#       Ranger
bspc rule -a konsole_desktop:autostart_ranger desktop='^1' state=floating rectangle="$width"x"$height_half"+"$right_x"+"$y_top" layer=below border=off
#       Terminal 
bspc rule -a konsole_desktop:autostart_term desktop='^1' state=floating rectangle="$width"x"$height_half"+"$right_x"+"$y_mid" layer=below border=off
# ytfzf
# bspc rule -a konsole:autostart_ytfzf desktop='^2' state=floating rectangle=900x939+5+71

# Launch Autostart Script
#. $HOME/coding/personal/scripting/autostart &


startup &
#konsole --class konsole_desktop --config ~/.config/konsole/konsole-themes/configs/Clear.conf &
