#!/bin/sh


#if [ $instance = autostart_htop ] ; then 
#    bspc rule -a autostart_htop desktop='^1' state=floating center=true rectangle=481x500+1434+69
#elif [ $class = autostart_htop ] ; then 
#    bspc rule -a autostart_htop desktop='^1' state=floating center=true rectangle=481x500+1434+69
#elif [ $wid = autostart_htop ] ; then 
#    bspc rule -a autostart_htop desktop='^1' state=floating center=true rectangle=481x500+1434+69
#fi
#
#if [ $instance = autostart_ranger ] ; then 
#    bspc rule -a autostart_ranger desktop='^1' state=floating center=true rectangle=481x939+5+69
#elif [ $class = autostart_ranger ] ; then 
#    bspc rule -a autostart_ranger desktop='^1' state=floating center=true rectangle=481x939+5+69
#elif [ $class = autostart_ranger ] ; then 
#    bspc rule -a autostart_ranger desktop='^1' state=floating center=true rectangle=481x939+5+69
#fi

wid=$1
class=$2
instance=$3
consequences=$4
title=$(xtitle "$wid")

dir="$HOME/.config/bspwm/temp"

echo >> $dir
echo "wid: $wid" >> $dir
echo "class: $class" >> $dir
echo "instance: $instance" >> $dir
echo "consequences: $consequences" >> $dir
echo >> $dir

if [ "$class" = "kitty" ]
then
    echo "desktop='^1' state=floating center=true rectangle=481x939+5+69"
    #bspc rule -a autostart_ranger desktop='^1' state=floating center=true rectangle=481x939+5+69
fi
#case "$instance" in
#	ranger)
#		eval "$consequences"
#		[ "$state" ] || echo "state=floating"
#		;;
#esac